version: '3.8'
services:
  postgres:
    image: postgres:17.4
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: logic
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: